### ISSUE TITLE
update site is down

### ISSUE THREAD

**Issue by mkrueske** [maximeAudrain/jenerate#12]
The update site [http://maximeaudrain.github.io/update/](http://maximeaudrain.github.io/update/) down, just responding with 404.

**Comment by maximeAudrain** [comment]
Dear mkrueske,

Thanks for your feedback, the site is online, but this update folder is the plugin update site and it does not display at all in a web browser. 

This update folder is only for the installation of the plugin, when you go to eclipse Help > Install New Software... and you enter the url http://maximeaudrain.github.io/update/, then you should be able to see the latest version of the plugin there for you to install.

Now I understand this can be confusing, but I guess this is a common issue with update sites (e.g I was looking at the update site for eclemma http://update.eclemma.org/ and it also displays strange results). 

Please, feel free to contact me if you experience other issues,

Cheers,

Maxime
