### ISSUE TITLE
Won't work with Neon.2 on MacOS

### ISSUE THREAD

**Issue by Ahg4goo9** [maximeAudrain/jenerate#13]
I installed the plugin but neither the shortcuts won't work nor do I see the menu item in preferences java. The installation went fine and the plugin shows up as installed.

**Comment by melloware** [comment]
Hmmm I am using Neon.3 an and Oxygen.1 on both OSX and Windows and they both work fine.  

So when you right click in the Java Code Editor you don't see the "Jenerate" option?

**Comment by Ahg4goo9** [comment]
Now that I changed to Photon it works flawlessly.
