### ISSUE TITLE
generated code is inserted at beginning, not at cursor position/end

### ISSUE THREAD

**Issue by wolfposd** [maximeAudrain/jenerate#17]
it feels weird that the generated methods are inserted at the beginning of the class, would be nicer at the current cursor position or simply at the end

**Comment by melloware** [comment]
Isn't it configurable you can say "Insert Before First Method" or "After Last Method" right in the dialog?

**Comment by wolfposd** [comment]
aah indeed it does, very hidden feature ;-)

**Comment by melloware** [comment]
No problem!
