### ISSUE TITLE
Can't install on Eclipse 2019-03 (4.11)

### ISSUE THREAD

**Issue by ivanmcshane** [maximeAudrain/jenerate#23]
Checking the eclipse marketplace I believe this is because the metadata indicates version support up to 2018-09 (4.9) only - https://marketplace.eclipse.org/content/jenerate

**Comment by melloware** [comment]
@maximeAudrain Can you please fix this or turn this project over to someone who will continue to maintain it?

**Comment by maximeAudrain** [comment]
Hi guys,

Sorry for the delay, I finally took the time to upgrade the metadata in the marketplace!

Please let me know if this works out for you or if I need to do additional operations?

Cheers,

**Comment by ivanmcshane** [comment]
Thanks @maximeAudrain, I tested there now on Eclipse version 2019-09 R (4.13.0) and it's working fine for me.

**Comment by melloware** [comment]
@ivanmcshane safe to close this issue then.  and @maximeAudrain thank you for the update we count on this plugin!!!

**Comment by ivanmcshane** [comment]
@melloware agreed, closing now.
