### ISSUE TITLE
Google Guava Support

### ISSUE THREAD

**Issue by melloware** [maximeAudrain/jenerate#3]
Just thought I would put this issue down for the backlog there are a lot of people that use Google Guava instead of Commons Lang.  Might be a nice additional sort of generator for the equals, hashcode, comparator etc?

Feel free to close if not interested but thought i would mention it!

nice work on this plugin!  very excited!

**Comment by maximeAudrain** [comment]
Hi Melloware!

Already done!! see my last commits from April 14-16!! https://github.com/maximeAudrain/jenerate/commits/master/org.jenerate

Please check it out if you want and let me know if it is ok for you or if you observe any bugs that could be fixed.

I am on the edge of deploying the plugin (I'm looking for a web site now to hold the plugin update site). I'll let you know when it is done!

Cheers,

Maxime

**Comment by melloware** [comment]
Awesome work! !! Don't forget to update the README.md for the Features section so users know.

**Comment by maximeAudrain** [comment]
Hi Melloware,

The plugin is ready! You can now generate all methods content with Guava!

Please have a look here for information on the plugin and how to install it
: http://maximeaudrain.github.io/
<https://mmm.cern.ch/owa/redir.aspx?C=Eqkrv9409kWOAU1zU-NuRuc9z1i9TNIIQLQHvCwvgfgbrxGDhWZcHHPXd69wBjNmTCY3ulfOHd0.&URL=http%3a%2f%2fmaximeaudrain.github.io%2f>

If you have any feedbacks, issues, etc... feel free to post them on
https://github.com/maximeAudrain/jenerate
<https://mmm.cern.ch/owa/redir.aspx?C=Eqkrv9409kWOAU1zU-NuRuc9z1i9TNIIQLQHvCwvgfgbrxGDhWZcHHPXd69wBjNmTCY3ulfOHd0.&URL=https%3a%2f%2fgithub.com%2fmaximeAudrain%2fjenerate>

Cheers,

Maxime



2015-04-17 15:36 GMT+02:00 Melloware <notifications@github.com>:
