### ISSUE TITLE
Commons Lang 3.4 Added new ToString Styles

### ISSUE THREAD

**Issue by melloware** [maximeAudrain/jenerate#4]
Just an FYI it looks like Commons Lang 3.4 added 2 new ToStringStyles you may want to add?

https://commons.apache.org/proper/commons-lang/release-notes/RELEASE-NOTES-3.4.txt

**Comment by maximeAudrain** [comment]
Hi Melloware,
I will try to take a look, but I must admit I am a bit more busy than a few months back (found a new job) :) I'll let you know when I will try to tackle this (probably in a couple of weeks).
In the meantime, if you want to take a look at how this could be done, please feel free! 

Cheers,

Maxime

**Comment by maximeAudrain** [comment]
Hi Melloware!

I am happy to announce that the feature you requested is now implemented and deployed in the latest 1.0.1 version of the plugin!

Please have a look to see if everything is alright!

Cheers, 

Maxime

**Comment by melloware** [comment]
Nice work!   I will grab the new version now.

**Comment by kdeenanauth** [comment]
Yay :metal: giving it a try later this week
