### ISSUE TITLE
Java 7 Objects Support

### ISSUE THREAD

**Issue by mfilser** [maximeAudrain/jenerate#5]
Hello maximeAudrain,
your Plugin is very good, i like it. Could you please add support for JDK Java 7 Objects class ?
There are also hints on the Guava site about Java 7 Objects.hash(Object...) and Objects.equals(Object, Object).
https://code.google.com/p/guava-libraries/wiki/CommonObjectUtilitiesExplained

This is the Objects Javadoc-Site:
http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html

Thank you in advance,
best regards

Martin

**Comment by kdeenanauth** [comment]
Hello!

If you are in a bind and really want it (like I did), there is a fork here that uses Objects.hashcode and Objects.equal but still relies on Guava for ToString:
https://github.com/kdeenanauth/jenerate

Regards!
Kevin

**Comment by maximeAudrain** [comment]
Hi guys,

Sorry for the late reply,

I will have some times in the following weeks to merge your fork and provide the Java 7 Objects equals and hashCode. I'll keep you posted!

Cheers,

Maxime

**Comment by maximeAudrain** [comment]
Hi Martin!

I am happy to announce that the feature you requested is now implemented and deployed in the latest 1.0.1 version of the plugin!

Please have a look to see if everything is alright!

Cheers, 

Maxime

**Comment by mfilser** [comment]
Hello Maxime,
the feature is really good and works as expected.
Thank you.

Best regards,
Martin

@kdeenanauth Thank you for your hint of your development, but i was busy the last weeks and not familiar with the eclipse plugin development, so i haven't enough time to test your work.
